name: liquid_progress_indicator
description: A progress indicator with water-like effect in Flutter. Works similarly to Flutters own ProgressIndicator.
version: 0.4.0
homepage: "https://github.com/JordanADavies/liquid_progress_indicator"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
